version: "3"
services:
  db:
    image: postgres:12.3
    container_name: online_store_db
    ports:
      - ${OS_DATABASE_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${OS_DATABASE_NAME}
      POSTGRES_USER: ${OS_DATABASE_USER}
      POSTGRES_PASSWORD: ${OS_DATABASE_PASSWORD}
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql



