version: "3"
services:
  db:
    image: postgres:12.3
    container_name: online_store_db
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - ./volumes/postgresql:/var/lib/postgresql



